/* ------------------------------------------------------------------
   The Budget Audiophile — catalog data
   A curated database of well-regarded affordable hi-fi gear, with a
   bias toward the low-key brands the community quietly swears by.
   Ratings blend measured performance + r/headphones, r/iems,
   r/BudgetAudiophile and reviewer consensus (Crinacle, Gizaudio,
   Headphones.com, ASR). Prices are typical street prices (USD),
   accurate to mid-2026 and prone to drift with coupons.
------------------------------------------------------------------ */

const CATEGORIES = [
  { id: "iems",       label: "IEMs",        blurb: "In-ear monitors — where chi-fi value lives" },
  { id: "headphones", label: "Headphones",  blurb: "Over- and on-ear, open & closed back" },
  { id: "dacamp",     label: "DACs & Amps", blurb: "Dongles, desktop sources & amplification" },
  { id: "players",    label: "Players",     blurb: "Hi-res DAPs & portable players" },
  { id: "speakers",   label: "Speakers",    blurb: "Powered & passive bookshelf" },
  { id: "turntables", label: "Turntables",  blurb: "Belt-drive & all-in-one" },
];

const PRODUCTS = [
  /* ------------------------------- IEMS ------------------------------ */
  {
    id: "zero2",
    name: "Salnotes Zero:2",
    brand: "7Hz",
    category: "iems",
    price: 25,
    rating: 4.6,
    ratingCount: 1120,
    signature: "Harman / Balanced",
    type: "Single 10mm DD",
    bestFor: "First IEM, students, gifting",
    tags: ["balanced", "value", "single-dd", "beginner"],
    image: "assets/zero2.jpg",
    images: ["assets/zero2.jpg", "assets/zero2-2.jpg", "assets/zero2-3.jpg"],
    blurb: "The sequel to the IEM that redefined $25 — now with tightened, weightier sub-bass.",
    review: "The original Salnotes Zero became a genre benchmark; the :2 keeps its reference-grade tuning while adding controlled low-end weight. Balanced, smooth, and shockingly mature for the money. When someone asks where to start in this hobby without spending real cash, this is still the answer.",
    pros: ["Reference tonality at $25", "Improved sub-bass vs. the original", "Detachable cable"],
    cons: ["Fit doesn't suit every ear", "Treble can be mildly splashy", "Stock tips are mediocre"],
    retailers: [{ name: "Linsoul", region: "Global" }, { name: "Amazon", region: "Global" }],
  },
  {
    id: "tanchjim-one",
    name: "One",
    brand: "Tanchjim",
    category: "iems",
    price: 25,
    rating: 4.4,
    ratingCount: 540,
    signature: "Neutral / Natural",
    type: "Single 10mm DD",
    bestFor: "Neutral-tuning lovers, all-rounder",
    tags: ["neutral", "value", "single-dd", "natural-timbre"],
    image: "assets/tanchjim-one.jpg",
    blurb: "An ultra-budget single-DD with disarmingly natural timbre — the DSP version adds app EQ.",
    review: "Tanchjim quietly makes some of the most natural-sounding budget IEMs around, and the One is the proof at pocket-money money. Tight, controlled bass, clean mids, and an unfatiguing top end. The optional DSP variant bundles a USB-C cable with full app EQ profiles — a clever way to fine-tune.",
    pros: ["Excellent natural tonality", "Transparent shell design", "DSP version adds Android EQ"],
    cons: ["Lean note weight", "Basic accessories", "Utilitarian stock cable"],
    retailers: [{ name: "Shenzhen Audio", region: "Global" }, { name: "Amazon", region: "Global" }],
  },
  {
    id: "ew200",
    name: "EW200",
    brand: "Simgot",
    category: "iems",
    price: 40,
    rating: 4.6,
    ratingCount: 880,
    signature: "Harman / Musical",
    type: "Single 10mm DD",
    bestFor: "Best sub-$50 single-DD, daily driver",
    tags: ["harman", "musical", "single-dd", "metal-build", "value"],
    image: "assets/ew200.jpg",
    images: ["assets/ew200.jpg", "assets/ew200-2.jpg", "assets/ew200-3.jpg"],
    blurb: "The community's favourite sub-$50 set — natural, musical, in a jewel-like all-metal shell.",
    review: "Simgot turned heads by making the EW200 sound more organic than sets twice its price. A dual-magnet, dual-cavity dynamic driver delivers a Harman-leaning tune that's musical without being sloppy, wrapped in a genuinely premium metal body. The default 'just buy it' recommendation in its bracket.",
    pros: ["Natural, musical tuning", "Premium all-metal build", "Superb value"],
    cons: ["Sub-bass slam is slightly soft", "Stock tips & cable are basic", "Short nozzle for some ears"],
    retailers: [{ name: "Linsoul", region: "Global" }, { name: "Amazon", region: "Global" }],
  },
  {
    id: "cadenza2",
    name: "Cadenza II",
    brand: "Kiwi Ears",
    category: "iems",
    price: 50,
    rating: 4.5,
    ratingCount: 470,
    signature: "Warm / Neutral",
    type: "Single 10mm titanium DD",
    bestFor: "Warm, smooth, long sessions",
    tags: ["warm", "smooth", "single-dd", "wide-stage"],
    image: "assets/cadenza2.png",
    blurb: "A refined, warm-leaning DD that favours balance over flash, with a big stage for the price.",
    review: "Kiwi Ears built a quiet reputation on tasteful tuning, and the Cadenza II is a fine example — warm yet transparent, with strong mids, smooth treble, and separation that punches above $50. A CNC aluminium faceplate adds a touch of class. Easy to live with for hours.",
    pros: ["Warm yet transparent", "Wide soundstage & good imaging", "CNC aluminium faceplate"],
    cons: ["May want tip-rolling for best fit", "Mid-bass punch is modest", "Not the last word in detail"],
    retailers: [{ name: "Linsoul", region: "Global" }, { name: "Amazon", region: "Global" }],
  },
  {
    id: "zerored",
    name: "ZERO:RED",
    brand: "Truthear × Crinacle",
    category: "iems",
    price: 55,
    rating: 4.6,
    ratingCount: 1340,
    signature: "Neutral + Sub-bass",
    type: "Dual DD (10 + 7.8mm)",
    bestFor: "Reference tuning with proper bass",
    tags: ["reference", "bass", "dual-dd", "tuning-adapter"],
    image: "assets/zerored.jpg",
    blurb: "A budget reference co-tuned with Crinacle — superb bass texture, beautifully controlled treble.",
    review: "The collaboration that became a budget staple. Two LCP dynamic drivers chase Crinacle's 'IEF neutral' target, delivering excellent bass quality and very well-judged treble. A swappable Bass+ adapter lets you dial in more low end on demand. Big nozzles mean small ears should check fit first.",
    pros: ["Reference-grade tuning", "Outstanding bass texture", "Bass+ tuning adapter included"],
    cons: ["Large nozzle — fit issues for small ears", "Can sound a touch safe", "Heavier than single-DD rivals"],
    retailers: [{ name: "Truthear", region: "Global" }, { name: "Linsoul", region: "Global" }],
  },
  {
    id: "artti-t10",
    name: "T10",
    brand: "Artti",
    category: "iems",
    price: 55,
    rating: 4.4,
    ratingCount: 380,
    signature: "W-shaped / Energetic",
    type: "14.2mm planar",
    bestFor: "Budget planar dynamics, big stage",
    tags: ["planar", "energetic", "spacious", "value"],
    image: "assets/artti-t10.jpg",
    blurb: "A standout budget planar — deep, fast bass and a vast, holographic soundstage for ~$55.",
    review: "Planar magnetic drivers used to mean spending real money; the Artti T10 brings their speed and slam to a budget price. Expect rumbly, textured bass, open transparent mids, and a 3D stage that belies the cost. Energetic up top, so treble-sensitive listeners should audition — but as a budget planar benchmark it's hard to beat.",
    pros: ["Big planar dynamics & soundstage", "Engaging, vivid presentation", "Quality silver-plated cable included"],
    cons: ["Can be peaky for the treble-sensitive", "Wants a little more power than a single DD", "The 'Pro' variant adds little"],
    retailers: [{ name: "Linsoul", region: "Global" }, { name: "Shenzhen Audio", region: "Global" }],
  },
  {
    id: "hexa",
    name: "Hexa",
    brand: "Truthear",
    category: "iems",
    price: 85,
    rating: 4.7,
    ratingCount: 1460,
    signature: "Neutral / Reference",
    type: "Hybrid (1DD + 3BA)",
    bestFor: "Reference tuning lovers, all genres",
    tags: ["neutral", "reference", "detailed", "value"],
    image: "assets/hexa.jpg",
    images: ["assets/hexa.jpg", "assets/hexa-2.jpg", "assets/hexa-3.jpg"],
    blurb: "Years on, still the sub-$100 benchmark reviewers keep falling back to.",
    review: "The Hexa is the IEM that made a lot of people stop chasing upgrades. A clean, slightly warm-neutral signature with excellent technical performance and a comfortable resin shell. Hard to find a fault at the price — it simply gets out of the way and lets the music through.",
    pros: ["Near-flawless reference tonality", "Resolving and clean", "Comfortable, lightweight shells"],
    cons: ["Lean/clinical for bassheads", "Modest stock accessories", "An older design now"],
    retailers: [{ name: "Truthear", region: "Global" }, { name: "Amazon", region: "Global" }],
  },
  {
    id: "nova",
    name: "Nova",
    brand: "Truthear",
    category: "iems",
    price: 150,
    rating: 4.6,
    ratingCount: 760,
    signature: "Harman / Reference",
    type: "Tribrid (1DD + 4BA)",
    bestFor: "Harman done right, technical listeners",
    tags: ["harman", "reference", "detailed", "tribrid"],
    image: "assets/nova.jpg",
    blurb: "Essentially the Harman tuning of a former $500 flagship, for a fraction of the price.",
    review: "The Nova delivers the kind of polished Harman response that used to cost five times as much — reviewers note you may even prefer its technical presentation to the old Moondrop Variations. A confident all-rounder that rewards good source gear and a proper seal.",
    pros: ["Reference Harman, done right", "Strong technicalities", "Great value vs. former flagships"],
    cons: ["Harman tuning is 'safe' / familiar", "8–10kHz can bite for some", "Needs a good seal"],
    retailers: [{ name: "Truthear", region: "Global" }, { name: "Linsoul", region: "Global" }],
  },
  {
    id: "daybreak",
    name: "Daybreak",
    brand: "CrinEar",
    category: "iems",
    price: 170,
    rating: 4.7,
    ratingCount: 540,
    signature: "Neutral / New Meta",
    type: "Tribrid (1DD + 2BA + 2 planar)",
    bestFor: "Reference 'New Meta' tuning, all genres",
    tags: ["neutral", "reference", "tribrid", "detailed"],
    image: "assets/daybreak.jpg",
    blurb: "The first IEM under Crinacle's own label — and instantly the most-hyped value set of the moment.",
    review: "CrinEar is Crinacle's in-house brand, and the Daybreak is its breakout: a full tribrid tuned to his 2025 'New Meta' target, with clean mids, a tasteful sub-bass shelf and a relaxed, fatigue-free top end. Reviewers crowned it the lowest-priced ticket to genuine reference tonality at launch. Stock arrives in batches, so grab it when it's in.",
    pros: ["Reference 'New Meta' tonality", "Full tribrid driver tech for the price", "Modular 3.5/4.4mm cable"],
    cons: ["Sold in limited batches", "Treble relaxed for treble-heads", "Brand-new brand, unproven support"],
    retailers: [{ name: "Linsoul", region: "Global" }, { name: "Hangout Audio", region: "Global" }],
  },
  {
    id: "portazo",
    name: "Portazo",
    brand: "Punch Audio",
    category: "iems",
    price: 189,
    rating: 4.5,
    ratingCount: 320,
    signature: "Bass-forward / V",
    type: "Hybrid (1DD + 2 planar)",
    bestFor: "Bassheads, EDM, hip-hop",
    tags: ["bass", "energetic", "hybrid", "fun"],
    image: "assets/portazo.jpg",
    blurb: "A late-2025 basshead darling — massive sub-bass slam that somehow keeps the mids clean.",
    review: "Punch Audio arrived with a statement: the Portazo pairs a dynamic driver with twin planars for a colossal sub-bass shelf, yet the mids stay surprisingly uncongested and the treble extends cleanly. It's unapologetically a fun, bass-first set — and it quickly became the reference for big budget bass done right.",
    pros: ["Class-leading sub-bass slam", "Mids stay clean despite the bass", "Light, comfy shells + modular cable"],
    cons: ["Too much bass for neutral fans", "Not an all-rounder", "Newer, less-proven brand"],
    retailers: [{ name: "Linsoul", region: "Global" }, { name: "Amazon", region: "Global" }],
  },
  {
    id: "aful-explorer",
    name: "Explorer",
    brand: "AFUL",
    category: "iems",
    price: 115,
    rating: 4.5,
    ratingCount: 640,
    signature: "Warm / Harman",
    type: "Hybrid (1DD + 2BA)",
    bestFor: "Smooth, non-fatiguing all-day listening",
    tags: ["warm", "smooth", "harman", "hybrid", "comfortable"],
    image: "assets/aful-explorer.jpg",
    blurb: "Trickle-down tech from AFUL's pricier sets makes this the go-to smooth-Harman pick under $120.",
    review: "AFUL built its name on resonance-control tech, and the Explorer brings it down to a friendly price. A bio-cellulose dynamic driver and twin BAs deliver a mellow Harman tune with a tasteful sub-bass lift — effortlessly smooth and non-fatiguing, in small, comfortable shells. The easy recommendation for listeners who can't stand harshness.",
    pros: ["Effortlessly smooth, inoffensive tuning", "Small, comfortable shells", "Trickle-down crossover tech"],
    cons: ["Laid-back can read as dull", "Not the most resolving", "Treble plays it safe"],
    retailers: [{ name: "HiFiGo", region: "Global" }, { name: "Linsoul", region: "Global" }],
  },
  {
    id: "supermix4",
    name: "SuperMix 4",
    brand: "Simgot",
    category: "iems",
    price: 150,
    rating: 4.4,
    ratingCount: 580,
    signature: "Harman / Natural",
    type: "Hybrid (DD + BA + planar + PZT)",
    bestFor: "Versatile, natural all-rounder",
    tags: ["harman", "natural", "hybrid", "detailed"],
    image: "assets/supermix4.jpg",
    blurb: "Four driver technologies in one budget shell — and, unusually, the tuning lives up to the gimmick.",
    review: "Simgot crammed a dynamic driver, a balanced armature, a planar and a PZT tweeter into the SuperMix 4 — a 'because we can' flex that happens to sound genuinely good. The result is a sub-bass-driven, natural-voiced Harman tune that stays versatile across genres. A constant value recommendation since launch.",
    pros: ["Unique four-technology driver array", "Natural, versatile tonality", "Punchy, controlled bass"],
    cons: ["PZT contribution is subtle", "Short warranty via some retailers", "Not night-and-day over simpler rivals"],
    retailers: [{ name: "Linsoul", region: "Global" }, { name: "Amazon", region: "Global" }],
  },

  /* ---------------------------- HEADPHONES --------------------------- */
  {
    id: "hd6xx",
    name: "HD 6XX",
    brand: "Sennheiser / Drop",
    category: "headphones",
    price: 220,
    rating: 4.8,
    ratingCount: 1840,
    signature: "Warm / Neutral",
    type: "Open-back",
    bestFor: "Vocals, acoustic, long listening",
    tags: ["open-back", "warm", "reference", "comfortable"],
    image: "assets/hd6xx.jpg",
    images: ["assets/hd6xx.jpg", "assets/hd6xx-2.jpg", "assets/hd6xx-3.jpg"],
    blurb: "The heart of the budget hi-fi hobby — an HD 650 in disguise at a friendlier price.",
    review: "If a single pair of headphones could be called the centre of gravity for this hobby, this is it. The 6XX delivers a slightly warm, intimate, almost analog presentation that flatters voices and strings. It needs a little amplification to truly open up, but the reward-for-money is extraordinary. A reference everything else gets compared to.",
    pros: ["Effortless, natural midrange", "Superb long-session comfort", "Easily modded & repairable"],
    cons: ["Benefits from a dedicated amp", "Intimate, narrow soundstage", "Clamp is tight out of the box"],
    retailers: [{ name: "Drop", region: "US" }, { name: "Amazon", region: "Global" }],
  },
  {
    id: "hd560s",
    name: "HD 560S",
    brand: "Sennheiser",
    category: "headphones",
    price: 200,
    rating: 4.5,
    ratingCount: 920,
    signature: "Neutral / Analytical",
    type: "Open-back",
    bestFor: "Mixing, critical listening, gaming",
    tags: ["open-back", "neutral", "reference", "easy-to-drive"],
    image: "assets/hd560s.jpg",
    blurb: "A genuinely neutral tuning that's honest about your recordings — and your gear.",
    review: "Where the 6XX charms, the 560S informs. Its tuning hews close to a studio reference target, with crisp detail retrieval and a wide, precise stage. Easy to drive from almost anything. The plastic build feels modest, but the sound punches far above the price.",
    pros: ["Reference-grade neutrality", "Wide, precise imaging", "Drives from a laptop or phone dongle"],
    cons: ["Build feels a touch plasticky", "Revealing of bad recordings", "Bass is polite, not punchy"],
    retailers: [{ name: "Sennheiser", region: "Global" }, { name: "Amazon", region: "Global" }],
  },
  {
    id: "dt770",
    name: "DT 770 PRO (80Ω)",
    brand: "Beyerdynamic",
    category: "headphones",
    price: 150,
    rating: 4.4,
    ratingCount: 1530,
    signature: "V-shaped / Detailed",
    type: "Closed-back",
    bestFor: "Studio tracking, bass, durability",
    tags: ["closed-back", "bass", "studio", "durable"],
    image: "assets/dt770.png",
    blurb: "A studio workhorse built like a tank, with plush velour and punchy lows.",
    review: "A decade-plus standard in studios worldwide. Strong sub-bass, sparkly treble, and the most comfortable velour pads in the business. The treble peak isn't for everyone, but the build and comfort are bombproof. The 80Ω version is the sweet spot for home use.",
    pros: ["Built to last for years", "Plush, cool velour pads", "Satisfying sub-bass"],
    cons: ["Sharp treble peak", "Coiled cable is non-detachable", "Recessed mids"],
    retailers: [{ name: "Thomann", region: "EU" }, { name: "Amazon", region: "Global" }],
  },
  {
    id: "shp9500",
    name: "SHP9500",
    brand: "Philips",
    category: "headphones",
    price: 75,
    rating: 4.3,
    ratingCount: 1120,
    signature: "Bright / Airy",
    type: "Open-back",
    bestFor: "Gaming, detail, big soundstage on a budget",
    tags: ["open-back", "bright", "spacious", "easy-to-drive", "value"],
    image: "assets/shp9500.jpg",
    blurb: "An astonishingly open, airy stage for the price of a nice dinner.",
    review: "A cult favourite for good reason: a huge soundstage, crisp detail, and feather-light comfort. The bass is lean and the treble can get zingy, but pair it with a warm source or a velour pad swap and it sings. The go-to first 'real' headphone for many.",
    pros: ["Cavernous soundstage", "Very light & comfortable", "Incredible value"],
    cons: ["Lean bass", "Treble can be hot", "Stock cable feels flimsy"],
    retailers: [{ name: "Amazon", region: "Global" }, { name: "Newegg", region: "US" }],
  },
  {
    id: "ft1-pro",
    name: "FT1 Pro",
    brand: "FiiO",
    category: "headphones",
    price: 199,
    rating: 4.5,
    ratingCount: 430,
    signature: "Neutral / Smooth",
    type: "Open-back planar",
    bestFor: "Budget planar, a Sundara alternative",
    tags: ["open-back", "planar", "neutral", "detailed"],
    image: "assets/ft1-pro.jpg",
    images: ["assets/ft1-pro.jpg", "assets/ft1-pro-2.jpg", "assets/ft1-pro-3.jpg"],
    blurb: "A 2025 budget-planar standout — neutral, smooth, and the new sub-$200 Sundara alternative.",
    review: "FiiO's first open-back planar takes the closed FT1's idea outdoors. A large in-house planar driver with a sapphire-and-aluminium-coated diaphragm delivers a clean, neutral, basically flaw-free tuning, and the bundle is generous — 4.4mm and 3.5mm cables plus a 6.35mm adapter. It needs a real amp or dongle to open up, but at the price the value is hard to beat.",
    pros: ["Neutral tuning with no real flaws", "Strong build + generous cable bundle", "Class-leading planar value"],
    cons: ["Heavy at ~374g", "Wants a proper amp to shine", "Tuning is safe rather than exciting"],
    retailers: [{ name: "FiiO", region: "Global" }, { name: "Amazon", region: "Global" }],
  },
  {
    id: "hd505",
    name: "HD 505",
    brand: "Sennheiser",
    category: "headphones",
    price: 250,
    rating: 4.4,
    ratingCount: 360,
    signature: "Smooth / Neutral-warm",
    type: "Open-back",
    bestFor: "A comfortable gateway open-back, vocals",
    tags: ["open-back", "smooth", "comfortable", "easy-to-drive"],
    image: "assets/hd505.jpg",
    blurb: "Sennheiser's freshest affordable open-back — a lighter, comfier gateway into audiophile sound.",
    review: "Released in early 2025, the HD 505 is Sennheiser's new on-ramp to the hobby. Its 120Ω driver gives a smooth, vocal-forward, fatigue-free presentation, with reduced clamp and a featherweight build, and it's easy enough to drive from a good dongle. Not the most resolving at the price, but supremely comfortable and likeable.",
    pros: ["Very comfortable & lightweight", "Smooth, non-fatiguing tuning", "Easy to drive, detachable cable"],
    cons: ["Not the most detailed at the price", "Bass is a touch polite", "Overlaps its own HD 560S"],
    retailers: [{ name: "Sennheiser", region: "Global" }, { name: "Amazon", region: "Global" }],
  },

  /* ---------------------------- DACs & AMPS -------------------------- */
  {
    id: "apple-dongle",
    name: "USB-C to 3.5mm",
    brand: "Apple",
    category: "dacamp",
    price: 9,
    rating: 4.3,
    ratingCount: 2100,
    signature: "Clean / Neutral",
    type: "Dongle DAC",
    bestFor: "Phones, IEMs, the budget starting line",
    tags: ["portable", "dongle", "value", "neutral"],
    image: "assets/apple-dongle.jpg",
    blurb: "The $9 dongle that measures cleaner than gear costing ten times more.",
    review: "An icon of value. Apple's tiny dongle delivers a clean, neutral, low-distortion output that drives most IEMs and efficient headphones effortlessly. It won't power hungry planars, but as a baseline 'do I even need more?' test, nothing beats it. Buy the US version — it's notably stronger than the EU one.",
    pros: ["Astonishingly clean output", "Trivially cheap", "Plug-and-play everywhere"],
    cons: ["Limited power", "No volume buttons on some platforms", "EU version is weaker than US"],
    retailers: [{ name: "Apple", region: "Global" }, { name: "Amazon", region: "Global" }],
  },
  {
    id: "dawn-pro",
    name: "Dawn Pro",
    brand: "Moondrop",
    category: "dacamp",
    price: 50,
    rating: 4.6,
    ratingCount: 690,
    signature: "Neutral / Clean",
    type: "Dongle DAC/Amp",
    bestFor: "Best budget balanced dongle",
    tags: ["portable", "dongle", "balanced", "neutral"],
    image: "assets/dawn-pro.jpg",
    blurb: "The default sub-$60 dongle — dual DAC chips and a proper balanced output.",
    review: "Twin Cirrus Logic CS43131 chips, a 4.4mm balanced jack alongside the 3.5mm, hardware volume buttons, and a clean neutral tune with a touch of low-end body. The Dawn Pro is widely cited as the best budget dual-DAC dongle, with measured performance that embarrasses its price.",
    pros: ["Excellent measured performance", "Balanced 4.4mm output", "Hardware volume buttons"],
    cons: ["No onboard app EQ", "Gets warm under load", "Plain design"],
    retailers: [{ name: "Linsoul", region: "Global" }, { name: "Amazon", region: "Global" }],
  },
  {
    id: "snowsky-nano",
    name: "Snowsky Retro Nano",
    brand: "FiiO",
    category: "dacamp",
    price: 63,
    rating: 4.5,
    ratingCount: 410,
    signature: "Clean / Fun",
    type: "Bluetooth + USB Dongle",
    bestFor: "Wireless + wired, charm-seekers",
    tags: ["portable", "bluetooth", "balanced", "ldac"],
    image: "assets/snowsky-nano.png",
    blurb: "FiiO's playful sub-brand in a cassette-deck shell — serious internals, irresistible charm.",
    review: "The breakout fun product of late 2025. Snowsky is FiiO's youthful spin-off, and the Retro Nano borrows the well-regarded BTR13's dual-CS43131 internals — then wraps them in a tiny retro cassette-deck body with a replaceable battery, LDAC Bluetooth, and tethered USB-DAC mode. Genuinely competent, genuinely delightful.",
    pros: ["Doubles as a wireless receiver", "Replaceable battery", "Standout retro design"],
    cons: ["Bulkier than pure dongles", "Tiny controls", "Not the most powerful"],
    retailers: [{ name: "Linsoul", region: "Global" }, { name: "Amazon", region: "Global" }],
  },
  {
    id: "qudelix5k",
    name: "5K",
    brand: "Qudelix",
    category: "dacamp",
    price: 109,
    rating: 4.8,
    ratingCount: 880,
    signature: "Transparent / Flexible",
    type: "Bluetooth DAC/Amp",
    bestFor: "Phone users, parametric EQ tinkerers",
    tags: ["portable", "bluetooth", "balanced", "eq"],
    image: "assets/qudelix5k.jpg",
    blurb: "A pocket powerhouse with the best parametric EQ app in the business.",
    review: "The 5K is a Swiss-army knife: wired or wireless, balanced output, every Bluetooth codec, and a phenomenal 20-band parametric EQ controlled from a polished app. It turns any headphone into your headphone. A perennial fan favourite that punches absurdly above its weight.",
    pros: ["Class-leading parametric EQ", "Balanced output, all codecs", "Tiny and well-supported"],
    cons: ["Fiddly physical buttons", "App has a learning curve", "Not a desktop powerhouse"],
    retailers: [{ name: "Amazon", region: "Global" }, { name: "Qudelix", region: "Global" }],
  },
  {
    id: "epz-tp35",
    name: "TP35 Pro",
    brand: "EPZ",
    category: "dacamp",
    price: 80,
    rating: 4.5,
    ratingCount: 320,
    signature: "Clean / Musical",
    type: "Dongle DAC/Amp",
    bestFor: "Versatile do-it-all dongle",
    tags: ["portable", "dongle", "balanced", "value"],
    image: "assets/epz-tp35.png",
    blurb: "A current darling of the dongle scene — clean, well-built, balanced, and a giant-killer.",
    review: "EPZ has quietly become one of the names to watch, and the TP35 line is why. Dual CS43131 chips, a 4.4mm balanced jack, a slightly musical tune, and genuinely nice cabling. Reviewers repeatedly call it the most versatile dongle under $100 — the Pro adds extra output and polish.",
    pros: ["Strong build & cabling", "Balanced output", "Great all-round value"],
    cons: ["Brand still lesser-known", "No Bluetooth", "Minimal onboard controls"],
    retailers: [{ name: "EPZ", region: "Global" }, { name: "Amazon", region: "Global" }],
  },
  {
    id: "fosi-k7",
    name: "K7",
    brand: "Fosi Audio",
    category: "dacamp",
    price: 189,
    rating: 4.5,
    ratingCount: 560,
    signature: "Warm / Powerful",
    type: "Desktop DAC/Amp",
    bestFor: "One-box desktop, gaming, hard-to-drive cans",
    tags: ["desktop", "balanced", "powerful", "bluetooth", "all-in-one"],
    image: "assets/fosi-k7.jpg",
    blurb: "Fosi's do-it-all desktop box — balanced power, Bluetooth, tone knobs and even a mic input.",
    review: "Fosi Audio is the poster child for 'low-key brand, ridiculous value,' and the K7 is its desktop statement. An AKM AK4493S DAC feeds a TPA6120 amp good for ~2,100mW, with aptX HD Bluetooth, optical/coax/USB inputs, a mic input, bass/treble controls, and both balanced and single-ended outputs. It drives demanding headphones with ease and leaves room to grow.",
    pros: ["Huge feature set for the price", "Plenty of clean power", "Onboard tone controls & mic input"],
    cons: ["Not the absolute cleanest measuring", "Tone controls are basic shelves", "Larger desk footprint"],
    retailers: [{ name: "Fosi Audio", region: "Global" }, { name: "Amazon", region: "Global" }],
  },
  {
    id: "fosi-za3",
    name: "ZA3",
    brand: "Fosi Audio",
    category: "dacamp",
    price: 90,
    rating: 4.6,
    ratingCount: 980,
    signature: "Punchy / Powerful",
    type: "Stereo power amp (TPA3255)",
    bestFor: "Driving passive bookshelf speakers",
    tags: ["power-amp", "class-d", "powerful", "value"],
    image: "assets/fosi-za3.jpg",
    blurb: "The single most-recommended budget speaker amp on r/BudgetAudiophile — staggering power per dollar.",
    review: "If you have passive bookshelf speakers and not much money, this is the internet's near-unanimous answer. The TPA3255-based ZA3 puts out anywhere from ~35W to well over 100W per channel depending on the power supply you feed it (choose the PSU carefully — it's critical), can be bridged to mono, and sounds clean and punchy. Pair it with a source and speakers and you have a real system for pennies.",
    pros: ["Enormous value & power", "Mono-bridgeable", "Tiny footprint, upgradeable PSU"],
    cons: ["PSU not always included — and it matters", "No DAC, streaming or remote", "Needs a separate preamp/source"],
    retailers: [{ name: "Fosi Audio", region: "Global" }, { name: "Amazon", region: "Global" }],
  },
  {
    id: "snowsky-melody",
    name: "Snowsky Melody",
    brand: "FiiO",
    category: "dacamp",
    price: 39,
    rating: 4.6,
    ratingCount: 380,
    signature: "Neutral / Natural",
    type: "Dongle DAC/Amp",
    bestFor: "Cheapest serious dongle, app EQ tinkerers",
    tags: ["portable", "dongle", "balanced", "eq", "value"],
    image: "assets/snowsky-melody.jpg",
    blurb: "A real wood-bodied dongle with dual flagship DAC chips and app EQ — for thirty-nine dollars.",
    review: "FiiO's Snowsky sub-brand keeps landing improbable value, and the Melody is the headline act: twin Cirrus Logic CS43131 chips, a balanced 4.4mm output, 10-band parametric EQ in the app, and a genuine North-American hardwood shell — all under $40. It won't bully demanding planars, but for IEMs it undercuts everything that sounds this clean.",
    pros: ["Astonishing value at $39", "Real hardwood build + balanced out", "Full 10-band app PEQ"],
    cons: ["Modest balanced power for hard loads", "No screen", "Wood shows fingerprints"],
    retailers: [{ name: "Aoshida", region: "Global" }, { name: "Amazon", region: "Global" }],
  },
  {
    id: "aiyima-a07max",
    name: "A07 Max",
    brand: "Aiyima",
    category: "dacamp",
    price: 66,
    rating: 4.5,
    ratingCount: 720,
    signature: "Clean / Neutral",
    type: "Stereo power amp (TPA3255)",
    bestFor: "Neutral, transparent speaker amplification",
    tags: ["power-amp", "class-d", "neutral", "value"],
    image: "assets/aiyima-a07max.jpg",
    blurb: "The neutral, measurement-clean rival to Fosi's punchier amps — and op-amp-rollable for tinkerers.",
    review: "Aiyima's A07 Max is the go-to when you want passive speakers driven cleanly rather than coloured. The TPA3255 design measures impressively low in distortion, adds a pre-out for flexibility, and lets you roll op-amps to taste. Feed it a good power supply and it delivers big, transparent headroom for around sixty-six dollars.",
    pros: ["Big, clean power for the price", "Op-amp rolling for tunability", "Pre-out adds flexibility"],
    cons: ["Needs a separate PSU (quality matters)", "No DAC or streaming built in", "Utilitarian looks"],
    retailers: [{ name: "Aiyima", region: "Global" }, { name: "Amazon", region: "Global" }],
  },
  {
    id: "qx13",
    name: "QX13",
    brand: "FiiO",
    category: "dacamp",
    price: 219,
    rating: 4.5,
    ratingCount: 290,
    signature: "Clean / Powerful",
    type: "Dongle DAC/Amp",
    bestFor: "Near-desktop power in your pocket",
    tags: ["portable", "dongle", "balanced", "powerful", "eq"],
    image: "assets/qx13.jpg",
    blurb: "A flagship dongle that brings near-desktop power and a colour screen to your phone.",
    review: "FiiO's QX13 is the 'do I even need a desktop amp?' dongle: a flagship ESS DAC, six op-amps and an XMOS core push up to ~900mW per channel, with a 2-inch colour display and onboard EQ wrapped in a carbon-fibre body. It drives surprisingly demanding loads for a pocket device — at the cost of size, heat and battery.",
    pros: ["Near-desktop power (~900mW)", "Flagship ESS DAC + carbon-fibre build", "Colour screen + onboard EQ"],
    cons: ["Pricey for a dongle", "Larger & heavier than rivals", "Runs warm, drains phone battery"],
    retailers: [{ name: "FiiO", region: "Global" }, { name: "Amazon", region: "Global" }],
  },
  {
    id: "wiim-ultra",
    name: "Amp Ultra",
    brand: "WiiM",
    category: "dacamp",
    price: 529,
    rating: 4.6,
    ratingCount: 410,
    signature: "Clean / Powerful",
    type: "Streaming integrated amp",
    bestFor: "A complete just-add-speakers system",
    tags: ["streaming", "powerful", "eq", "all-in-one"],
    image: "assets/wiim-ultra.jpg",
    blurb: "The all-in-one streaming amp that made a complete hi-fi system this easy — and this affordable.",
    review: "The WiiM Amp Ultra rolls a 100W/ch Class-D amplifier, an ESS Sabre DAC, room correction, parametric EQ and every major streaming service into one box with a colour touchscreen. Add a pair of passive speakers and you have a genuinely high-performing, dead-simple system. Reviewers called it the future of affordable amplification.",
    pros: ["Streaming + room EQ + touchscreen in one", "Strong measured performance", "Superb app & ecosystem"],
    cons: ["The priciest pick here", "Class-D, not for tube lovers", "Some early firmware quirks"],
    retailers: [{ name: "WiiM", region: "Global" }, { name: "Amazon", region: "Global" }],
  },

  /* ------------------------------ SPEAKERS --------------------------- */
  {
    id: "r1280t",
    name: "R1280T",
    brand: "Edifier",
    category: "speakers",
    price: 120,
    rating: 4.5,
    ratingCount: 3400,
    signature: "Warm / Easy",
    type: "Powered bookshelf",
    bestFor: "Desktops, first real speakers, vinyl",
    tags: ["powered", "warm", "value", "beginner"],
    image: "assets/r1280t.jpg",
    blurb: "The default recommendation for a first pair of real powered speakers.",
    review: "Plug in power, plug in your source, done. The R1280T offers a warm, pleasant sound, dual RCA inputs (great for a turntable), tone controls, and a remote — all for the price of a video game. Not the most resolving, but endlessly likeable and forgiving.",
    pros: ["Truly plug-and-play", "Two inputs + tone controls", "Includes a remote"],
    cons: ["Bass rolls off without a sub", "Classic looks won't suit all", "Not the last word in detail"],
    retailers: [{ name: "Edifier", region: "Global" }, { name: "Amazon", region: "Global" }],
  },
  {
    id: "diamond121",
    name: "Diamond 12.1",
    brand: "Wharfedale",
    category: "speakers",
    price: 349,
    rating: 4.6,
    ratingCount: 410,
    signature: "Warm / Refined",
    type: "Passive bookshelf",
    bestFor: "A warm, forgiving step into real hi-fi",
    tags: ["passive", "warm", "refined", "musical"],
    image: "assets/diamond121.jpg",
    blurb: "A perennial budget-audiophile darling — warm, forgiving and beautifully finished.",
    review: "Wharfedale's Diamond line has been a giant-killer for decades, and the 12.1 carries the torch. Warm, smooth and refined, it flatters a wide range of music and is endlessly easy to listen to, with a fit and finish that looks far dearer than it is. Partner it with the Fosi ZA3 and a cheap source for a complete system that punches well above its weight.",
    pros: ["Warm, forgiving, musical sound", "Gorgeous fit & finish", "Easy to drive"],
    cons: ["Needs a separate amplifier", "Polite up top for detail-chasers", "Wants stands & breathing room"],
    retailers: [{ name: "Wharfedale", region: "Global" }, { name: "Crutchfield", region: "US" }],
  },
  {
    id: "q1meta",
    name: "Q1 Meta",
    brand: "KEF",
    category: "speakers",
    price: 400,
    rating: 4.7,
    ratingCount: 320,
    signature: "Refined / Detailed",
    type: "Passive bookshelf",
    bestFor: "A real high-end step-up with an amp",
    tags: ["passive", "refined", "detailed", "imaging"],
    image: "assets/q1meta.png",
    images: ["assets/q1meta.png", "assets/q1meta-2.png", "assets/q1meta-3.png"],
    blurb: "KEF's Uni-Q coaxial driver — and now MAT tech — brings genuine high-end imaging to a budget.",
    review: "The successor to the beloved Q150, the Q1 Meta is where budget meets bona-fide hi-fi. The concentric Uni-Q driver produces a precise, holographic image and a wonderfully even response, now refined with KEF's Metamaterial Absorption Technology. They need a separate amplifier, but partnered well they outclass almost anything near the price. A long-term keeper.",
    pros: ["Pinpoint imaging from Uni-Q", "Refined, even tonality", "Beautiful, compact cabinets"],
    cons: ["Requires a separate amplifier", "Wants stands & space to breathe", "Bass benefits from a sub"],
    retailers: [{ name: "KEF", region: "Global" }, { name: "Crutchfield", region: "US" }],
  },

  /* ----------------------------- TURNTABLES -------------------------- */
  {
    id: "rt81",
    name: "RT81",
    brand: "Fluance",
    category: "turntables",
    price: 250,
    rating: 4.5,
    ratingCount: 880,
    signature: "Warm / Solid",
    type: "Belt-drive, built-in preamp",
    bestFor: "Vinyl starters who want room to grow",
    tags: ["belt-drive", "preamp", "warm", "upgradeable"],
    image: "assets/rt81.jpg",
    blurb: "A weighty wood-plinth deck with an AT cartridge and a switchable preamp.",
    review: "The RT81 feels like a grown-up turntable at an entry price: a real MDF plinth, an Audio-Technica AT95-style cartridge, and a built-in preamp you can switch off as you upgrade. A satisfying, warm-leaning sound and a clear upgrade path make it a smart first deck.",
    pros: ["Switchable built-in preamp", "Solid wood-veneer plinth", "Quality starter cartridge"],
    cons: ["Manual operation only", "No USB output", "Dust cover scratches easily"],
    retailers: [{ name: "Fluance", region: "US" }, { name: "Amazon", region: "Global" }],
  },
  {
    id: "lp60x",
    name: "AT-LP60X",
    brand: "Audio-Technica",
    category: "turntables",
    price: 150,
    rating: 4.2,
    ratingCount: 4100,
    signature: "Easy / Automatic",
    type: "Belt-drive, fully automatic",
    bestFor: "Total beginners, set-and-forget vinyl",
    tags: ["belt-drive", "automatic", "preamp", "beginner"],
    image: "assets/lp60x.jpg",
    blurb: "The fully-automatic deck that's introduced a generation to records.",
    review: "Press a button, the arm drops, the music plays, and it lifts itself at the end. The LP60X removes every barrier to spinning vinyl, with a built-in preamp for plugging straight into powered speakers. The cartridge isn't upgradeable, but for ease and price it's unmatched.",
    pros: ["Fully automatic operation", "Built-in switchable preamp", "Foolproof for beginners"],
    cons: ["Non-upgradeable cartridge", "Lightweight, resonant plinth", "Limited tweakability"],
    retailers: [{ name: "Amazon", region: "Global" }, { name: "Audio-Technica", region: "Global" }],
  },

  /* ------------------------------- PLAYERS --------------------------- */
  {
    id: "echo-mini",
    name: "Snowsky Echo Mini",
    brand: "FiiO",
    category: "players",
    price: 50,
    rating: 4.4,
    ratingCount: 350,
    signature: "Fun / Capable",
    type: "Portable player (DAP)",
    bestFor: "A charming, pocketable first DAP",
    tags: ["portable", "dap", "balanced", "bluetooth", "value"],
    image: "assets/echo-mini.png",
    blurb: "A retro cassette-style player with dual flagship DAC chips and balanced out — for fifty dollars.",
    review: "FiiO's Snowsky Echo Mini went semi-viral on looks alone, but the hardware backs it up: dual CS43131 chips, a 4.4mm balanced output and hi-res support in a pocketable body styled like a tiny cassette deck. The interface is basic and big libraries bog it down, but as a fun, focused player for $50 it's a delight.",
    pros: ["Remarkable hardware for $50", "Charming retro design", "Balanced output, pocketable"],
    cons: ["Clunky UI, weak with big libraries", "No gapless playback", "Basic Bluetooth, no playlists"],
    retailers: [{ name: "Linsoul", region: "Global" }, { name: "Amazon", region: "Global" }],
  },
];
